# Generated by Django 4.2.6 on 2023-11-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='projectId',
        ),
        migrations.AddField(
            model_name='developer',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='developer',
            name='specialization',
            field=models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('DEVOPS', 'DevOps'), ('UX/UI', 'UX/UI')], default='FRONTEND', max_length=10),
        ),
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
