# Generated by Django 4.2.6 on 2023-11-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_developer__id_remove_developer_projectid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
