# Generated by Django 4.2.6 on 2023-11-03 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to='main.developer')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_credentials',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.projectcredentials'),
        ),
    ]
