# Generated by Django 4.2.6 on 2023-11-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_publication_remove_project_project_credentials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcredentials',
            name='users',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='project_id',
        ),
        migrations.AddField(
            model_name='project',
            name='project_credentials',
            field=models.ManyToManyField(to='main.developer'),
        ),
        migrations.DeleteModel(
            name='ProjectCredentials',
        ),
    ]
