# Generated by Django 4.2.6 on 2023-11-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_projectcredentials_users_delete_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
