# Generated by Django 4.2.6 on 2023-11-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_developer_options_remove_project_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_credentials',
            new_name='developers',
        ),
    ]
