# Generated by Django 4.2.6 on 2023-11-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_project_credentials_project_developers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['name']},
        ),
    ]
