# Generated by Django 4.2.6 on 2023-11-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_developer_completed_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['id']},
        ),
    ]
