# Generated by Django 4.2.6 on 2023-11-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_developer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_name',
            new_name='user',
        ),
    ]
