# Generated by Django 4.2.6 on 2023-11-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_project_id_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='developers',
        ),
    ]
