# Generated by Django 4.2.6 on 2023-11-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_project_developers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['name']},
        ),
    ]
