# Generated by Django 4.2.6 on 2023-11-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_project_developers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(default=None, to='main.developer'),
        ),
    ]
