# Generated by Django 4.2.6 on 2023-11-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_project_developers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['id']},
        ),
    ]
