# Generated by Django 4.2.6 on 2023-11-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_developer_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
