# Generated by Django 4.2.6 on 2023-11-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_delete_article_delete_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=100)),
                ('credentials', models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('DEVOPS', 'DevOps'), ('UX/UI', 'UX/UI')], default='FRONTEND', max_length=100)),
                ('state', models.CharField(choices=[('TO_DO', 'To-do'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='TO_DO', max_length=100)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField()),
            ],
        ),
    ]
