# Generated by Django 4.2.6 on 2023-11-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(default=None, to='main.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimation',
            field=models.IntegerField(default=1),
        ),
    ]
