# Generated by Django 4.2.6 on 2023-11-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_project_tasks_task_estimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='developers',
            field=models.ManyToManyField(default=None, to='main.developer'),
        ),
    ]
